config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :todos do
    member do
      post 'check'
    end
  end

  resources :users, only: [:show, :new, :create, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

  validates :title, presence: true, length: { in: 3..100 }
  validates :memo,  length: { maximum: 255 }
  validate :duedate_cannot_be_in_the_past

  # 登録日時より前の日時は登録できない
  def duedate_cannot_be_in_the_past
    return unless duedate < Date.today
    errors.add(:duedate, 'can not be in the past')
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :todos, dependent: :destroy

  validates :name, presence: true
  # TODO: 正直、ここの正規表現がわかっていない...
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    uniqueness: { case_sensitive: true },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: 'hello world!'
  end
end

app/controllers/sessions_controller.rb
include ApplicationHelper

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    # メアドとパスワード認証
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'invalid email or password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/todos_controller.rb
include ApplicationHelper

class TodosController < ApplicationController
  def index
    redirect_to login_url, alert: 'ログインしてください' unless logged_in?

    @todos = Todo.where(user_id: session[:user_id])
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.checked_flg = false
    @todo.user_id = session[:user_id]

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_url, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check
    @todo = Todo.find(params[:id])

    if @todo.update_attributes(checked_flg: params[:checked_flg])
    else
      puts 'error'
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :memo, :duedate)
  end
end

app/controllers/users_controller.rb
require 'sessions_helper'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  helper_method :current_user, :logged_in?

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        # 登録時に他のユーザーでログイン状態でなければ、登録ユーザーでログイン
        unless logged_in?
          # 登録時にログインする
          log_in @user
        end

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # ログイン処理
  def log_in(user)
    session[:user_id] = user.id
  end

  # ログアウト処理
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 現在ログインしているユーザーを返す
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしているかどうか確認
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数に与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(todo) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :memo %>
    <%= f.text_area :memo %>
  </div>

  <div class="field">
    <%= f.label :duedate %>
    <%= f.date_select :duedate %>
  </div>

  <div class="actions">
    <%= f.submit 'Create', class: 'button success' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>TODO編集</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo, {:class => 'button'} %> |
<%= link_to 'Destroy', @todo, method: :delete, :class => 'button alert' %> |
<%= link_to 'Back', todos_path, {:class => 'button info'} %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Todos</h1>
<h2><%= current_user.name %>
<h3>全タスク：<%= @todos.count %></h3>
<h3>未完了タスク：<%= @todos.where(checked_flg:false).count %></h3>
<ul class="no-bullet todo-lists">
  <% @todos.where(checked_flg:false).each do |todo| %>
    <li class="row todo-list">
      <%= check_box_tag 'checked_flg', todo.id, todo.checked_flg, {:checked_flg => todo.checked_flg, :class => 'small-1 large-2 columns todo-check'} %>
      <span class="small-10 large-8 columns">
        <%= link_to todo.title, edit_todo_path(todo), {:class => 'text-left todo-title'} %><br>
        <span><%= todo.memo %></span><br>
        <span><%= todo.duedate %></span>
      </span>
      <%= link_to '削除', todo, {method: :delete, :class => 'small-1 large-2 columns'} %>
    </li>
  <% end %>
</ul>
<br>
<%= link_to 'New Todo', new_todo_path, :class => 'button' %>
<br>
<h3>完了タスク：<%= @todos.where(checked_flg:true).count %></h3>
<ul class="no-bullet todo-lists">
  <% @todos.where(checked_flg:true).each do |todo| %>
    <li class="row todo-list">
      <%= check_box_tag 'checked_flg', todo.id, todo.checked_flg, {:checked_flg => todo.checked_flg, :class => 'small-1 large-2 columns'} %>
      <span class="small-10 large-8 columns">
        <%= link_to todo.title, edit_todo_path(todo), {:class => 'text-left todo-title'} %><br>
        <span><%= todo.memo %></span><br>
        <span><%= todo.duedate %></span>
      </span>
      <%= link_to '削除', todo, {method: :delete, :class => 'small-1 large-2 columns'} %>
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checked flg:</strong>
  <%= @todo.checked_flg %>
</p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @todo.memo %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @todo.duedate %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Destroy', @todo, method: :delete %> |
<%= link_to 'Back', todos_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit "Create New User", class:"button" %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? %>
<h1>Hello, <%= current_user.name %></h1>
<% end %>
<p>こちらはユーザー一覧です。</p>
<table>
  <thead>
    <tr>
      <% if Rails.env.development? %>
        <th>Id</th>
      <% end %>
      <th>Name</th>
      <th>Email</th>
      <th>Create Date</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <% if Rails.env.development? %>
          <td><%= user.id %></td>
        <% end %>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<p class="user-name">
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p class="user-email">
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Todo', todos_path, class: 'button' %>
<%= link_to 'App Setting', user_path, class: 'button secondary' %>
<br>
<%= link_to 'Log out', logout_path, method: :delete, class: 'button alert' %>